#! usr/bin/python3
import nmap

scanner = nmap.PortScanner()

print("welcome to nmap scanning tool!!")
print("------------")
ip_addr = input("enter the IP address tos can :")
print("the ip entered is:", ip_addr)
print("type of entered ip:", type(ip_addr))


resp = input("""\n enter the type of scan you want to do
              1. SYN SCAN
              2. UDP SCAN
              3. comprehensive scan
              4. tcp connect scan
              5. sctp init scan
              6. tcp ACK scan
              7. tcp Window Scan \n""")

print("you have selected:", resp)

resp_dict = {
    '1': ['-sS -SV -vv', 'tcp'],           
    '2': ['-sU -sV -vv', 'udp'],           
    '3': ['-sS -vv -p- -A', 'tcp'],        
    '4': ['-sT -vv', 'tcp'],              
    '5': ['-sY -vv', 'sctp'],              
    '6': ['-sA -vv', 'tcp'],               
    '7': ['-sW -vv', 'tcp']                
}

if resp not in resp_dict.keys():
        print("enter  a valid option");
else:
        
        print("Nmap version:", scanner.nmap_version())
        scanner.scan(ip_addr , "1-1024", resp_dict[resp][0])
        
        if scanner[ip_addr].state() == 'up':
               print ("\n host is up scan results:")
        
        for proto in scanner[ip_addr].all_protocols():
               print("\nProtocol :{}".format(proto))
               print("open ports :{}".format(','.join(map(str,scanner[ip_addr][proto].keys()))))
        for port, info in scanner[ip_addr][proto].items():
                print("\n Port : {} \nService :{}\n State : {}".format(port,info['name'],info['state']))
             
